# Generated by Django 4.2.3 on 2023-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pins", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saved",
            name="pin",
        ),
        migrations.AddField(
            model_name="saved",
            name="saves",
            field=models.ManyToManyField(
                blank=True, related_name="saves", to="pins.pin"
            ),
        ),
    ]
