# Generated by Django 4.2.3 on 2023-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pins", "0002_remove_saved_pin_saved_saves"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="url",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
